use_frameworks!

platform :ios, '10.0'

ENV['SWIFT_VERSION'] = '5'  

target 'binaryLib_Example' do
  pod 'binaryLib', :path => '../'

  target 'binaryLib_Tests' do
    inherit! :search_paths

    
  end
end
